
version: "3.8"

services: 
  mysql:
    container_name: emsdb
    image: mysql
    environment:
      MYSQL_DATABASE: "ems_db"
      MYSQL_ROOT_PASSWORD: "Emsdb@321"
    ports:
      - "3306:3306"
    volumes:
      - emsdbvol:/var/lib/mysql
    networks:
      - ems_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pEmsdb@321"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  backend:
    build:
      context: ./backend
    container_name: emsbackend
    ports:
      - "5000:5000"
    networks:
      - ems_network
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 10 && node index.js"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://emsbackend:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
    container_name: emsfrontend
    ports:
      - "80:80"
    networks:
      - ems_network
    restart: always
    depends_on:
      - backend

volumes:
  emsdbvol:

networks:
  ems_network:
