apiVersion: apps/v1
kind: Deployment
metadata:
  name: emsbackenddeploy
  labels:
    app: emsbackendapp
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emsbackendPod
  template:
    metadata:
      labels:
        app: emsbackendPod
    spec:
      containers:
        - name: emsbackendcon
          image: pankajarya12345/emsbackend:latest 
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_HOST
              value: "mysqlsvc.ems.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Emsdb@321"
            - name: DB_NAME
              value: "ems_db"
          

