apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
  namespace: ems
spec:
  selector:
    app: emsappmysql 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

